//
//  NameListDetailInteractor.swift
//  learnVIP
//
//  Created by Nathaniel Andrian on 21/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NameListDetailBusinessLogic
{
  func doLoadData(request: NameListDetail.Load.Request)
}

protocol NameListDetailDataStore
{
  var name: String { get set }
}

class NameListDetailInteractor: NameListDetailBusinessLogic, NameListDetailDataStore
{
    var name: String = ""
    
  var presenter: NameListDetailPresentationLogic?
  var worker: NameListDetailWorker?
  
  
  // MARK: Do something
  
  func doLoadData(request: NameListDetail.Load.Request)
  {
    worker = NameListDetailWorker()
      worker?.getName(name: name, completion: { data in
          let response = NameListDetail.Load.Response(name: data)
          self.presenter?.presentSomething(response: response)
      })
    
     
    
  }
}
