//
//  NameListDetailPresenter.swift
//  learnVIP
//
//  Created by Nathaniel Andrian on 21/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NameListDetailPresentationLogic
{
  func presentSomething(response: NameListDetail.Load.Response)
}

class NameListDetailPresenter: NameListDetailPresentationLogic
{
  weak var viewController: NameListDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: NameListDetail.Load.Response)
  {
      let viewModel = NameListDetail.Load.ViewModel(name: response.name)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
