//
//  NameListRouter.swift
//  learnVIP
//
//  Created by Nathaniel Andrian on 15/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NameListRoutingLogic
{
  func routeToNameListDetail(segue: UIStoryboardSegue?)
}

protocol NameListDataPassing
{
  var dataStore: NameListDataStore? { get }
}

class NameListRouter: NSObject, NameListRoutingLogic, NameListDataPassing
{
  weak var viewController: NameListViewController?
  var dataStore: NameListDataStore?
  
  // MARK: Routing
  
  func routeToNameListDetail(segue: UIStoryboardSegue?)
  {
      let destinationVC = NameListDetailViewController()
      var destinationDS = destinationVC.router!.dataStore!
      passDataToNameListDetail(source:  dataStore!, destination: &destinationDS)
      navigateToNameListDetail(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToNameListDetail(source: NameListViewController, destination: NameListDetailViewController)
  {
      source.show(destination, sender: source.self)
 
  }
  
  // MARK: Passing data
  
  func passDataToNameListDetail(source: NameListDataStore, destination: inout NameListDetailDataStore)
  {
      let selectedRow = viewController?.nameListView.tableView.indexPathForSelectedRow?.row
      let selectedName = source.name?[selectedRow!].name
      guard let finalName = selectedName else { return  }
      destination.name = finalName
  }
}
