//
//  NameListPresenter.swift
//  learnVIP
//
//  Created by Nathaniel Andrian on 15/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NameListPresentationLogic
{
  func presentData(response: NameListScene.Load.Response)
}

class NameListPresenter: NameListPresentationLogic
{
  weak var viewController: NameListDisplayLogic?
  
  // MARK: Do something
  
  func presentData(response: NameListScene.Load.Response)
  {
      let viewModel = NameListScene.Load.ViewModel(nameList: response.nameList)
    viewController?.displayData(viewModel: viewModel)
      
  }
}
